
# Create database from mysql dump
- name: prepare mysql dump restore
  template:
    src: "matomo.sql.j2"
    dest: "{{ webserver_document_root }}/matomo.sql"
    owner: "{{ matomo_user }}"
    group: "{{ matomo_user }}"
    force: no
  register: motomo_sql_dump_create

- name: restore dump
  mysql_db:
    name: "{{ matomo_db_name }}"
    target: "{{ webserver_document_root }}/matomo.sql"
    state: import
    login_host: "{{ matomo_db_host }}"
    login_port: "{{ matomo_db_port }}"
    login_user: "{{ matomo_db_root_user }}"
    login_password:  "{{ matomo_db_root_password }}"
  ignore_errors: yes
  when: motomo_sql_dump_create | changed

# create config.ini.php with default settings
- name: Create config.ini.php
  template:
    src:   "config.ini.php.j2"
    dest:  "{{ matomo_install_dir }}/config/config.ini.php"
    owner: "{{ matomo_user }}"
    group: "{{ matomo_user }}"
    mode:  0664
    force: no
  register: motomo_config_create
